### ISSUE TITLE
13.1.3 breaks on parsing error due to object rest spread

### ISSUE THREAD

**Issue by jbadan** [blackflux/object-scan#1138]
This commit removed `@babel/plugin-proposal-object-rest-spread`: https://github.com/blackflux/object-scan/commit/f947c3a772683db1d264d59e6a253d166e439ecb

Ex error:

```
ERROR in /node_modules/object-scan/lib/index.js
Module parse failed: Unexpected token (212:4)
You may need an appropriate loader to handle this file type.
     useArraySelector: true,
     strict: true,
     ...opts
   };
```

This has caused a couple issues in our consuming library. Would it be possible to add it back?

Thanks!

**Comment by simlu** [comment]
Oh very interesting. Let me take a look at this. Cheers for the ticket and pr!

**Comment by simlu** [comment]
Which node version are you using? I guess this was a breaking change...

**Comment by jbadan** [comment]
No problem! I'm not sure how to get the code coverage up to pass the tests in that pr though :) 

We got this error using 12.15.0

**Comment by simlu** [comment]
Weird, this works fine for us. Do you have a minimal test case to reproduce? Just so I have something to go on. Thank you!

**Comment by simlu** [comment]
Using node6

```sh
$ yarn run build-clean
$ yarn docker circleci/node:6
$ node tmp.js
```

where `tmp.js`

```js
const objectScan = require('./lib/index');
console.log(objectScan(['**'])({}));
```

I get this

```sh
/user/project/lib/index.js:212
    ...opts
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user/project/tmp.js:1:82)
```

However if I use node8 with `yarn docker circleci/node:8` everything works fine.

So I'm suspecting that you're running node6?

If you provide a test case I am more than happy to investigate further!

**Comment by jbadan** [comment]
Hi @simlu! 
I'm definitely not using node 6. 
I'll update this when I have some more time to put together an example. My current use case is not open source. Thanks for the quick responses!

**Comment by simlu** [comment]
@jbadan It looks like you have some sort of compile script? Any clue to what is going on in there? Because I can use object-scan fine in node10+ as documented in my last post, so something must be different for your use case
